// Feature 006 — FR-003, FR-004, FR-040, FR-041 (ADR-019): the contract map is verified against the contract in
// both directions; every failure case has a fixture (generated by fixtures/api-map/gen-fixtures.mjs).
import { describe, expect, it } from "vitest";
import { fixture, runScript } from "./run.js";

const check = (dir: string) => {
  const base = fixture("api-map", dir);
  return runScript("check-api-map.mjs", [
    "--map",
    `${base}/api-map.yaml`,
    "--bundle",
    `${base}/bundle.yaml`,
    "--constitution",
    `${base}/constitucion.md`,
    "--mvp-docs",
    `${base}/mvp`,
    "--specs",
    `${base}/specs`,
    "--schemes",
    `${base}/securitySchemes`,
  ]);
};

describe("check:api-map", () => {
  it("passes on a coherent map and reports the count per status", () => {
    const r = check("ok");
    expect(r.status, r.output).toBe(0);
    expect(r.output).toContain("Map: 2 built, 1 planned, 1 deprecated, 1 retired");
  });

  it.each([
    ["contract-without-entry", "listThings"],
    ["built-without-operation", "listThings"],
    ["built-field-mismatch", "ingestEvents"],
    ["built-security-mismatch", "ingestEvents"],
    ["built-capability-mismatch", "ingestEvents"],
    ["tag-outside-consumer", "putFlags"],
    ["capability-outside-vocabulary", "putFlags"],
    ["scheme-file-missing", "nowhere"],
    ["scheme-file-malformed", "adminToken"],
    ["feature-unknown", "099"],
    ["roadmap-unknown", "nowhere"],
    ["planned-with-feature", "not a feature"],
    ["built-with-roadmap", "not a roadmap item"],
    ["source-broken", "Nowhere"],
    ["duplicate-operation-id", "putFlags"],
    ["duplicate-method-path", "put /v1/admin/merchants/{merchantId}/flags"],
    ["status-unknown", "someday"],
    ["deprecated-without-flag", "listOldThings"],
    ["flag-without-deprecated", "listOldThings"],
    ["retired-present", "listGone"],
    ["retired-without-version", "listGone"],
    ["merchant-id-outside-admin", "listDecisions"],
    ["public-with-security", "getHealth"],
  ])("%s fails naming %s", (dir, needle) => {
    const r = check(dir);
    expect(r.status, r.output).toBe(1);
    expect(r.output).toContain(needle);
  });

  it("without the MVP documents it warns and does not fail", () => {
    const r = check("mvp-absent");
    expect(r.status, r.output).toBe(0);
    expect(r.output).toContain("warning");
  });

  it("the real map and the real contract are coherent", () => {
    const r = runScript("check-api-map.mjs", []);
    expect(r.status, r.output).toBe(0);
    expect(r.output).toMatch(/Map: \d+ built, \d+ planned/);
  });
});
