// Feature 040 — US1 (FR-008..FR-012; ADR-044): what a consumer copies of the contract is emitted here,
// in the shape OPE-Web publishes, from the real bundle. The emitter is JavaScript; its shape is
// declared here and every rule of the artifact is asserted against the bundle, not against a copy.
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { beforeAll, describe, expect, it } from "vitest";
import { parse } from "yaml";

interface Emitter {
  generateConsumerArtifacts: (apiDts: string, problemTypesDts: string) => [string, string][];
  CONSUMER: string;
}

interface Operation {
  operationId: string;
  tags?: string[];
  "x-required-capabilities"?: string[];
  "x-idempotency"?: unknown;
  requestBody?: { content?: Record<string, { schema?: { $ref?: string } }> };
}
interface Bundle {
  info: { version: string };
  paths: Record<string, Record<string, Operation>>;
  components: {
    schemas: Record<string, { type?: string; required?: string[]; properties?: Record<string, unknown> }>;
  };
}

const METHODS = ["get", "put", "post", "delete", "patch", "options", "head", "trace"];
const API_DTS = "// GENERATED by scripts/contract-types.mjs from x\nexport interface operations {}\n";
const PROBLEM_DTS =
  "// GENERATED by scripts/contract-problem-types-lib.mjs from y\nexport type ProblemSlug = never;\n";

/** The emitted files by name, as text. */
let files: Map<string, string>;
let consumer: string;
let bundle: Bundle;

/** The admin operations of the bundle, in its order. */
function adminOperations(): Operation[] {
  const found: Operation[] = [];
  for (const item of Object.values(bundle.paths)) {
    for (const method of METHODS) {
      const op = item[method];
      if (op?.tags?.includes(consumer)) found.push(op);
    }
  }
  return found;
}

/** The value a generated module exports, read from its text as the consumer would. */
async function moduleOf(name: string): Promise<Record<string, unknown>> {
  const dir = path.join(import.meta.dirname, "fixtures", "consumer-artifacts");
  const { mkdirSync, writeFileSync } = await import("node:fs");
  mkdirSync(dir, { recursive: true });
  const file = path.join(dir, name);
  writeFileSync(file, files.get(name) ?? "", "utf8");
  return (await import(`${pathToFileURL(file).href}?t=${Date.now()}`)) as Record<string, unknown>;
}

interface Capabilities {
  CONTRACT: { version: string; sha256: string };
  CONSUMER: string;
  CAPABILITIES: string[];
  OPERATIONS: Record<string, { capabilities: string[]; idempotent: boolean; versioned: boolean }>;
}
interface Constraints {
  CONTRACT: { version: string; sha256: string };
  CONSTRAINTS: Record<string, { required: string[]; fields: Record<string, Record<string, unknown>> }>;
}

let capabilities: Capabilities;
let constraints: Constraints;

beforeAll(async () => {
  const mod = (await import(
    pathToFileURL(path.resolve("scripts/contract-consumer-artifacts-lib.mjs")).href
  )) as Emitter;
  consumer = mod.CONSUMER;
  files = new Map(
    mod
      .generateConsumerArtifacts(API_DTS, PROBLEM_DTS)
      .map(([file, content]) => [path.basename(file), content]),
  );
  bundle = parse(readFileSync(path.resolve("contracts/dist/openapi.yaml"), "utf8")) as Bundle;
  capabilities = (await moduleOf("capabilities.js")) as unknown as Capabilities;
  constraints = (await moduleOf("constraints.js")) as unknown as Constraints;
});

describe("generated/contract/: the eight files", () => {
  it("emits exactly the files the consumer copies, every one with the generating script in its header", () => {
    expect([...files.keys()].sort()).toEqual([
      "api.d.ts",
      "capabilities.d.ts",
      "capabilities.js",
      "constraints.d.ts",
      "constraints.js",
      "identity.json",
      "openapi.yaml",
      "problem-types.d.ts",
    ]);
    for (const name of ["capabilities.js", "capabilities.d.ts", "constraints.js", "constraints.d.ts"]) {
      expect(files.get(name)?.split("\n")[0]).toBe(
        "// GENERATED by scripts/contract-consumer-artifacts-lib.mjs from contracts/dist/openapi.yaml — DO NOT EDIT BY HAND.",
      );
    }
    expect(files.get("openapi.yaml")?.split("\n")[0]).toMatch(
      /^# GENERATED by scripts\/contract-consumer-artifacts-lib\.mjs from /,
    );
    expect(files.get("api.d.ts")).toBe(API_DTS);
    expect(files.get("problem-types.d.ts")).toBe(PROBLEM_DTS);
  });

  it("identity.json names the version and the sha256 of the copied bundle, and no commit", () => {
    const identity = JSON.parse(files.get("identity.json") ?? "{}") as Record<string, unknown>;
    expect(Object.keys(identity).sort()).toEqual(["$comment", "sha256", "version"]);
    expect(identity["$comment"]).toMatch(/^GENERATED by scripts\/contract-consumer-artifacts-lib\.mjs from /);
    expect(identity["version"]).toBe(bundle.info.version);
    const sha = createHash("sha256")
      .update(files.get("openapi.yaml") ?? "")
      .digest("hex");
    expect(identity["sha256"]).toBe(sha);
    expect(capabilities.CONTRACT).toEqual({ version: bundle.info.version, sha256: sha });
    expect(constraints.CONTRACT).toEqual(capabilities.CONTRACT);
  });

  it("is deterministic: a second run gives the same bytes", async () => {
    const mod = (await import(
      pathToFileURL(path.resolve("scripts/contract-consumer-artifacts-lib.mjs")).href
    )) as Emitter;
    const again = new Map(
      mod.generateConsumerArtifacts(API_DTS, PROBLEM_DTS).map(([f, c]) => [path.basename(f), c]),
    );
    expect(again).toEqual(files);
  });
});

describe("capabilities: operation → capabilities and idempotency", () => {
  it("lists every admin operation of the bundle, in its order, and none other", () => {
    const expected = adminOperations().map((op) => op.operationId);
    expect(Object.keys(capabilities.OPERATIONS)).toEqual(expected);
    expect(capabilities.CONSUMER).toBe(consumer);
  });

  it("copies x-required-capabilities as declared and derives idempotent from x-idempotency", () => {
    for (const op of adminOperations()) {
      expect(capabilities.OPERATIONS[op.operationId]).toMatchObject({
        capabilities: op["x-required-capabilities"],
        idempotent: "x-idempotency" in op,
      });
    }
  });

  it("derives versioned from the If-Match the operation declares: exactly the four writes with a witness (feature 043)", () => {
    const versioned = Object.entries(capabilities.OPERATIONS)
      .filter(([, o]) => o.versioned)
      .map(([id]) => id)
      .sort();
    expect(versioned).toEqual([
      "publishMerchantConfiguration",
      "publishPlatformConfiguration",
      "publishTreatmentDefaults",
      "updateMerchantProfile",
    ]);
    expect(files.get("capabilities.d.ts") ?? "").toContain(
      "readonly updateMerchantProfile: {\n    readonly capabilities: readonly ['merchants:write']\n    readonly idempotent: false\n    readonly versioned: true\n  }",
    );
  });

  it("getOperator asks for nothing: the only empty list, admitted because it identifies the principal", () => {
    expect(capabilities.OPERATIONS["getOperator"]).toEqual({
      capabilities: [],
      idempotent: false,
      versioned: false,
    });
    const empty = Object.entries(capabilities.OPERATIONS).filter(([, o]) => o.capabilities.length === 0);
    expect(empty.map(([id]) => id)).toEqual(["getOperator"]);
  });

  it("CAPABILITIES is the sorted union, and the declaration carries the same literals", () => {
    const union = [...new Set(Object.values(capabilities.OPERATIONS).flatMap((o) => o.capabilities))].sort();
    expect(capabilities.CAPABILITIES).toEqual(union);
    const dts = files.get("capabilities.d.ts") ?? "";
    expect(dts).toContain(
      `export declare const CAPABILITIES: readonly [${union.map((c) => `'${c}'`).join(", ")}]`,
    );
    expect(dts).toContain(
      "readonly getOperator: {\n    readonly capabilities: readonly []\n    readonly idempotent: false\n    readonly versioned: false\n  }",
    );
    expect(dts).toContain("export type OperationId = keyof typeof OPERATIONS");
  });
});

describe("constraints: what a form can verify of each request body", () => {
  /** Every object schema some admin request body names, directly or through another. */
  function expectedSchemas(): string[] {
    const wanted = new Set<string>();
    const refOf = (ref: unknown): string | undefined =>
      typeof ref === "string" && ref.startsWith("#/components/schemas/")
        ? ref.slice("#/components/schemas/".length)
        : undefined;
    const visit = (name: string): void => {
      if (wanted.has(name)) return;
      const schema = bundle.components.schemas[name];
      if (schema?.type !== "object") return;
      wanted.add(name);
      for (const each of Object.values(schema.properties ?? {})) {
        const p = each as { $ref?: unknown; items?: { $ref?: unknown } };
        const inner = refOf(p.$ref) ?? refOf(p.items?.$ref);
        if (inner !== undefined) visit(inner);
      }
    };
    for (const op of adminOperations()) {
      const name = refOf(op.requestBody?.content?.["application/json"]?.schema?.$ref);
      if (name !== undefined) visit(name);
    }
    return [...wanted].sort();
  }

  it("has one key per request-body object schema, sorted, each with the required of its schema", () => {
    const expected = expectedSchemas();
    expect(expected.length).toBeGreaterThan(0);
    expect(Object.keys(constraints.CONSTRAINTS)).toEqual(expected);
    for (const name of expected) {
      expect(constraints.CONSTRAINTS[name]?.required).toEqual(
        bundle.components.schemas[name]?.required ?? [],
      );
    }
    const dts = files.get("constraints.d.ts") ?? "";
    for (const name of expected) expect(dts).toContain(`  readonly ${name}: MessageConstraints`);
    expect(dts).toContain("export type ConstrainedSchema = keyof typeof CONSTRAINTS");
  });

  it("reads bounds, items and minimums as the bundle declares them", () => {
    expect(constraints.CONSTRAINTS["MerchantCreate"]).toEqual({
      required: ["origins", "signature", "displayName"],
      fields: {
        displayName: { type: "string", minLength: 1, maxLength: 120 },
        storeUrl: { type: "string", pattern: "^https?://", minLength: 1, maxLength: 255 },
        contact: { type: "object", ref: "MerchantContact" },
        notes: { type: "string", minLength: 1, maxLength: 2000 },
        origins: { type: "array", minItems: 1, maxItems: 20, items: { type: "string", maxLength: 255 } },
        signature: { type: "boolean" },
      },
    });
    expect(constraints.CONSTRAINTS["CredentialRotation"]?.fields["graceSeconds"]).toEqual({
      type: "integer",
      minimum: 0,
    });
  });

  // Feature 041 (ADR-045): the identity of the merchant and its contact reach the consumer.
  it("the identity of the merchant: the contact is a schema of its own, with a format the form can check", () => {
    expect(constraints.CONSTRAINTS["MerchantContact"]).toEqual({
      required: ["name", "email"],
      fields: {
        name: { type: "string", minLength: 1, maxLength: 120 },
        email: { type: "string", minLength: 3, maxLength: 254, format: "email" },
        phone: { type: "string", minLength: 1, maxLength: 32 },
        role: { type: "string", minLength: 1, maxLength: 80 },
      },
    });
    expect(constraints.CONSTRAINTS["MerchantProfileInput"]?.required).toEqual(["displayName"]);
    expect(constraints.CONSTRAINTS["MerchantProfileInput"]?.fields["contact"]).toEqual({
      type: "object",
      ref: "MerchantContact",
    });
    // The edition replaces the identity whole, so it requires the witness of what it read (feature 043).
    expect(capabilities.OPERATIONS["updateMerchantProfile"]).toEqual({
      capabilities: ["merchants:write"],
      idempotent: false,
      versioned: true,
    });
  });

  it("a property that references another object schema is { type: 'object', ref }, and that schema is listed", () => {
    const refs = Object.entries(constraints.CONSTRAINTS).flatMap(([, s]) =>
      Object.values(s.fields).filter((f) => typeof f["ref"] === "string"),
    );
    expect(refs.length).toBeGreaterThan(0);
    for (const field of refs) {
      expect(field).toEqual({ type: "object", ref: field["ref"] });
      expect(constraints.CONSTRAINTS).toHaveProperty(String(field["ref"]));
    }
  });

  it("emits neither a default nor a description: the omission is the server's and the label the application's", () => {
    const text = files.get("constraints.js") ?? "";
    expect(text).not.toMatch(/"default":/);
    expect(text).not.toMatch(/"description":/);
  });
});
